version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - cd frontend && npm install
      - pip install -r backend/requirements.txt

  build:
    commands:
      - cd frontend && npm run build

  post_build:
    commands:
      - chmod +x scripts/*.sh

artifacts:
  files:
    - frontend/dist/**/*
    - appspec.yml
    - scripts/**/*
    - backend/**/*
  discard-paths: no
